# Generated by Django 4.1.4 on 2022-12-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='storybookStory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
