# Generated by Django 4.1.4 on 2022-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_website_storybookstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='storybookStory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
